// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-accounts.ts
import { createClient } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List the signed-in user's Branch accounts (id, name, industry, tier). Excludes soft-deleted accounts.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)."),
    search: z.string().optional().describe("Case-insensitive substring match on account name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("active_accounts").select("id, name, industry, tier, motion, arr").eq("user_id", ctx.getUserId()).order("name").limit(limit ?? 50);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-account.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function extractPov(md) {
  if (!md) return null;
  const lines = md.split(/\r?\n/);
  const povIdx = lines.findIndex((l) => /^##\s+(00\s+[—-]\s+)?strategic pov\b/i.test(l));
  if (povIdx < 0) return null;
  let endIdx = lines.length;
  for (let i = povIdx + 1; i < lines.length; i++) {
    if (/^##\s+/.test(lines[i])) {
      endIdx = i;
      break;
    }
  }
  let startIdx = povIdx;
  for (let i = povIdx - 1; i >= 0; i--) {
    if (/^##\s+key numbers\b/i.test(lines[i])) {
      startIdx = i;
      break;
    }
    if (/^##\s+/.test(lines[i])) break;
  }
  return lines.slice(startIdx, endIdx).join("\n").slice(0, 5e3);
}
var get_account_default = defineTool2({
  name: "get_account",
  title: "Get account",
  description: "Fetch a single account with its open opportunities and the Strategic POV excerpt from its current dossier.",
  inputSchema: {
    account_id: z2.string().uuid().describe("Account UUID (use list_accounts to discover).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ account_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const [{ data: acct, error: aErr }, { data: opps }, { data: dossier }] = await Promise.all([
      sb.from("active_accounts").select("id, name, industry, tier, motion, arr, notes").eq("user_id", userId).eq("id", account_id).maybeSingle(),
      sb.from("opportunities").select("id, name, stage, amount, close_date").eq("user_id", userId).eq("account_id", account_id).order("close_date", { ascending: true }),
      sb.from("account_dossiers").select("markdown, updated_at").eq("user_id", userId).eq("account_id", account_id).order("updated_at", { ascending: false }).limit(1).maybeSingle()
    ]);
    if (aErr) return { content: [{ type: "text", text: aErr.message }], isError: true };
    if (!acct) return { content: [{ type: "text", text: "Account not found" }], isError: true };
    const pov = extractPov(dossier?.markdown ?? null);
    const payload = { account: acct, opportunities: opps ?? [], strategic_pov: pov, dossier_updated_at: dossier?.updated_at ?? null };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-opportunities.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_opportunities_default = defineTool3({
  name: "list_opportunities",
  title: "List opportunities",
  description: "List the signed-in user's opportunities, optionally filtered by account or stage.",
  inputSchema: {
    account_id: z3.string().uuid().optional().describe("Optional account UUID filter."),
    stage: z3.string().optional().describe("Optional exact stage match."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ account_id, stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser3(ctx).from("opportunities").select("id, name, account_id, stage, amount, close_date, next_step").eq("user_id", ctx.getUserId()).order("close_date", { ascending: true }).limit(limit ?? 50);
    if (account_id) q = q.eq("account_id", account_id);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-strategy-threads.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_strategy_threads_default = defineTool4({
  name: "list_strategy_threads",
  title: "List strategy threads",
  description: "List the signed-in user's strategy chat threads (id, title, linked account/opportunity, last activity).",
  inputSchema: {
    account_id: z4.string().uuid().optional().describe("Optional filter to threads linked to this account."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ account_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser4(ctx).from("strategy_threads").select("id, title, linked_account_id, linked_opportunity_id, updated_at, created_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (account_id) q = q.eq("linked_account_id", account_id);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/search-knowledge-items.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_knowledge_items_default = defineTool5({
  name: "search_knowledge_items",
  title: "Search knowledge items",
  description: "Case-insensitive substring search across the user's Knowledge Items (title + summary).",
  inputSchema: {
    query: z5.string().min(2).describe("Search term."),
    limit: z5.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const like = `%${query}%`;
    const { data, error } = await supabaseForUser5(ctx).from("knowledge_items").select("id, title, summary, category, confidence_score").eq("user_id", ctx.getUserId()).or(`title.ilike.${like},summary.ilike.${like}`).order("confidence_score", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "odbjjklumdsuqdvkgwyv";
var mcp_default = defineMcp({
  name: "dynamic-mcp",
  title: "Dynamic (Branch AE)",
  version: "0.1.0",
  instructions: "Tools for Corey Hartin's Branch expansion territory in the Dynamic app. Use list_accounts / get_account / list_opportunities to inspect the 14 enterprise accounts and their strategic POVs. Use list_strategy_threads to find recent strategy conversations, and search_knowledge_items to look up captured Knowledge Items. All tools act as the signed-in user; RLS applies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_accounts_default, get_account_default, list_opportunities_default, list_strategy_threads_default, search_knowledge_items_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
