CREATE TABLE public.function_configs (
  function_name text PRIMARY KEY,
  primary_model text NOT NULL,
  fallback_model text,
  notes text,
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.function_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY function_configs_service_only ON public.function_configs
  USING (false) WITH CHECK (false);

INSERT INTO public.function_configs (function_name, primary_model, fallback_model, notes) VALUES
  ('grade-transcript', 'claude-sonnet-4-6', 'claude-haiku-4-5-20251001', null),
  ('dojo-score', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-6', null),
  ('grade-lesson-response', 'claude-sonnet-4-6', null, 'legacy gateway URL — needs gateway elimination pass'),
  ('car-mode-score', 'google/gemini-2.5-flash', null, null),
  ('car-mode-audio-score', 'google/gemini-2.5-flash', null, null),
  ('dojo-roleplay-score', 'google/gemini-2.5-flash', null, null),
  ('dojo-review-score', 'google/gemini-2.5-flash', null, null),
  ('score-micro-drill', 'google/gemini-2.5-flash', null, null),
  ('score-original-response', 'google/gemini-2.5-flash', null, null),
  ('grade-mock-call', 'google/gemini-2.5-flash', null, null),
  ('grade-objection-drill', 'google/gemini-2.5-flash', null, null),
  ('mock-call', 'google/gemini-2.5-flash', null, null),
  ('playbook-roleplay', 'google/gemini-2.5-flash', null, null),
  ('explain-score', 'google/gemini-2.5-flash', null, null),
  ('generate-flashcards', 'google/gemini-2.5-flash', null, null),
  ('generate-lesson-content', 'google/gemini-2.5-flash', null, null),
  ('extract-scenarios', 'google/gemini-3-flash-preview', null, null),
  ('extract-tasks', 'google/gemini-3-flash-preview', null, null),
  ('extract-tactics', 'google/gemini-2.5-flash', null, null),
  ('build-resource', 'google/gemini-3-flash-preview', null, null),
  ('operationalize-resource', 'google/gemini-3-flash-preview', null, null),
  ('suggest-resource-uses', 'google/gemini-3-flash-preview', null, null),
  ('suggest-templates', 'google/gemini-3-flash-preview', null, null),
  ('generate-execution-draft', 'google/gemini-3-flash-preview', null, null),
  ('generate-call-goals', 'google/gemini-2.5-flash', null, null),
  ('generate-stage-playbook', 'google/gemini-2.5-flash', null, null),
  ('generate-playbooks', 'google/gemini-2.5-flash', null, null),
  ('enrich-account', 'google/gemini-2.5-flash', null, null),
  ('discover-resources', 'google/gemini-2.5-pro', null, null),
  ('discover-contacts', 'google/gemini-2.5-flash', null, null),
  ('classify-signal', 'google/gemini-2.5-flash', null, null),
  ('classify-resource', 'google/gemini-2.5-flash', null, null),
  ('batch-extract-kis', 'google/gemini-2.5-flash', null, null),
  ('detect-knowledge-gaps', 'google/gemini-2.5-flash', null, null),
  ('parse-account-screenshot', 'google/gemini-2.5-flash', null, null),
  ('parse-account-synopsis', 'google/gemini-2.5-flash', null, null),
  ('parse-calendar-screenshot', 'google/gemini-2.5-flash', null, null),
  ('parse-opp-synopsis', 'google/gemini-2.5-flash', null, null),
  ('parse-screenshot', 'google/gemini-2.5-flash', null, null),
  ('parse-uploaded-file', 'google/gemini-2.5-flash', null, null),
  ('parse-claude-import', 'google/gemini-2.5-flash', null, null),
  ('preprocess-transcript', 'google/gemini-2.5-flash', null, null),
  ('prioritize-accounts', 'google/gemini-3-flash-preview', null, null),
  ('source-icp-accounts', 'google/gemini-2.5-flash', null, null),
  ('pdf-ocr', 'google/gemini-2.5-flash', null, 'vision'),
  ('analyze-deal-outcome', 'google/gemini-2.5-flash', null, null),
  ('analyze-sentiment', 'google/gemini-2.5-flash-lite', null, null),
  ('analyze-call', 'claude-haiku-4-5-20251001', null, null),
  ('clean-baseline', 'google/gemini-2.5-flash', null, null),
  ('territory-copilot', 'google/gemini-2.5-pro', 'google/gemini-2.5-flash', null),
  ('voice-command', 'google/gemini-2.5-flash', null, null),
  ('weekly-battle-plan', 'google/gemini-2.5-flash', null, null),
  ('strategy-chat', 'gpt-4o', 'claude-sonnet-4-6', null),
  ('strategy-transform-output', 'gpt-5-mini', 'gpt-4o', null),
  ('strategy-summarize-upload', 'google/gemini-2.5-flash-lite', null, null),
  ('strategy-detect-proposals', 'google/gemini-2.5-flash', null, null),
  ('derive-library-cards', 'google/gemini-2.5-flash', null, null),
  ('run-strategy-eval-synthesis', 'gpt-5', null, null),
  ('expand-prompt', 'claude-haiku-4-5-20251001', null, null),
  ('extract-strategy-memory', 'claude-haiku-4-5-20251001', null, null),
  ('elevenlabs-tts-stream', 'eleven_turbo_v2_5', null, 'not an LLM — audio model'),
  ('batch-regrade-now', 'claude-sonnet-4-6', null, null);