
UPDATE public.ki_curriculum SET
  drill_scenario = $sc$Priya Shah, VP Growth at a global streaming service you already partner with, pauses mid-QBR and says: "Look — Adjust is in here pitching us hard on unified attribution. Honest question, why shouldn't we just consolidate on them?"$sc$,
  drill_spoken_task = $ts$Respond to Priya in a single turn — acknowledge Adjust honestly, then draw the line where your solution wins for her specific priority.$ts$,
  drill_model_answer = $ma$When a prospect names a competitor I lean in, not away: 'Good — they're a real option, and here's what they do well.' Then I hand them the honest version of where each of us fits best. Most reps go quiet or trash-talk; doing neither is the move. The prospect remembers who treated them like an adult.$ma$,
  drill_rubric = '[{"c":"Acknowledges the competitor as a real, credible option — no trash-talk, no deflection","must":true},{"c":"Names one specific area where the competitor is legitimately strong"},{"c":"Draws a concrete line where our approach fits the buyer''s stated priority"},{"c":"Ends with a question or invitation that keeps the buyer talking"}]'::jsonb,
  drill_teach_script = $ds$The tactic: confidently discuss competitors. Three moves — acknowledge them as a real option, name one thing they do well, then draw an honest line to where you fit best. Use it any time a prospect names a competitor by name, or when you know they're evaluating alternatives you haven't discussed yet. Why it matters: going silent or trash-talking both erode trust. Treating the buyer like an adult who can weigh trade-offs is what makes you the trusted advisor in the room. Now listen to elite: When a prospect names a competitor I lean in, not away: 'Good — they're a real option, and here's what they do well.' Then I hand them the honest version of where each of us fits best. Most reps go quiet or trash-talk; doing neither is the move. The prospect remembers who treated them like an adult.$ds$,
  drill_ready = true
WHERE concept_id = 'CPP01' AND order_in_concept = 1;

UPDATE public.ki_curriculum SET
  drill_scenario = $sc$You've just inherited a large media account — a national broadcaster — from a departing AE. On your first call, Marcus Okafor, their SVP Digital, opens with: "So what are you here to sell me?"$sc$,
  drill_spoken_task = $ts$Reset the frame in your first two sentences — steer away from a product pitch and toward proving the original purchase is winning.$ts$,
  drill_model_answer = $ma$When I inherit an account my first conversation is not about new products. It's: 'I want to understand the problems you bought us to solve and whether we're actually solving them — tell me where we're falling short.' Until they tell me the original purchase is winning, I have no right to ask for more budget, and any pitch I make lands as a vendor trying to upsell instead of a partner who earned a bigger seat.$ma$,
  drill_rubric = '[{"c":"Does NOT pitch a new product, feature, or tier in the response","must":true},{"c":"Explicitly asks about the problems the account originally bought to solve"},{"c":"Invites honest feedback on where the current solution is falling short"}]'::jsonb,
  drill_teach_script = $ds$The tactic: earn the right to expand. Before you pitch anything new, run a value audit — surface the problems they originally bought you to solve and confirm honestly whether you're solving them. Use it on every inherited account and at the start of any expansion motion, especially when a stakeholder changes or a renewal is approaching. Why it matters: customers won't spend more with a vendor whose current work isn't landing. Skip this step and every expansion pitch reads as an upsell, not a partnership. Now listen to elite: When I inherit an account my first conversation is not about new products. It's: 'I want to understand the problems you bought us to solve and whether we're actually solving them — tell me where we're falling short.' Until they tell me the original purchase is winning, I have no right to ask for more budget, and any pitch I make lands as a vendor trying to upsell instead of a partner who earned a bigger seat.$ds$,
  drill_ready = true
WHERE concept_id = 'ERX01' AND order_in_concept = 1;

UPDATE public.ki_curriculum SET
  drill_scenario = $sc$Elena Vasquez, Head of Lifecycle Marketing at a mid-market fashion retailer, shrugs on the demo call: "Our current tool works fine. What would even change if we switched?"$sc$,
  drill_spoken_task = $ts$Paint the promised-land contrast in two beats — the hidden pain of today, then the concrete better world in ninety days.$ts$,
  drill_model_answer = $ma$I paint two pictures in the same breath: where they are now — the manual exports, the angry exec emails, the conversion drop they've stopped talking about — and where they could be, concretely, in 90 days. Then I draw the line between the two with our product. The contrast does the selling.$ma$,
  drill_rubric = '[{"c":"Names at least one specific, concrete current-state pain — not abstract","must":true},{"c":"Paints a specific future-state outcome with a time horizon or measurable delta"},{"c":"Explicitly draws the line between today and the future using the product"}]'::jsonb,
  drill_teach_script = $ds$The tactic: the promised-land narrative. Paint two pictures in the same breath — the messy today they've stopped noticing and the concrete better future in ninety days — then draw the line between the two with your product. Use it when the buyer sounds satisfied with the status quo, or when your product solves a pain they've grown numb to. Why it matters: features don't move people, contrast does. Once a buyer sees the gap between what is and what could be, urgency creates itself. Now listen to elite: I paint two pictures in the same breath: where they are now — the manual exports, the angry exec emails, the conversion drop they've stopped talking about — and where they could be, concretely, in 90 days. Then I draw the line between the two with our product. The contrast does the selling.$ds$,
  drill_ready = true
WHERE concept_id = 'VPR01' AND order_in_concept = 1;

UPDATE public.ki_curriculum SET
  drill_scenario = $sc$On a discovery call with Devon Marsh, IT Director at a regional bank, he cuts you off mid-slide: "Honestly, this feels like a nice-to-have. We're not going to prioritize it this year."$sc$,
  drill_spoken_task = $ts$Answer Devon's pushback with your first beat — do not rebut, do not sell. Welcome it.$ts$,
  drill_model_answer = $ma$When a buyer pushes back, my first move is to thank them for it — out loud. "Honestly, I appreciate you saying that. Most people would have just ghosted me. Tell me more about where that's coming from." That single beat does more than any rebuttal: it kills the adversarial dynamic and makes the prospect comfortable telling me the real reason — which is almost never the first one they said.$ma$,
  drill_rubric = '[{"c":"Does NOT rebut, defend, or reframe the objection in the first sentence","must":true},{"c":"Explicitly thanks or acknowledges the buyer for raising the concern"},{"c":"Asks a follow-up that invites the real, deeper reason underneath"}]'::jsonb,
  drill_teach_script = $ds$The tactic: welcome the objection. Your first move is a genuine thank-you, out loud — no rebuttal, no reframe, no counter-argument. Then ask them to tell you more about where it's coming from. Use it the instant a buyer pushes back, especially on price, timing, or "we're happy with what we have." Why it matters: reps who rebut trigger defensiveness and only ever get the surface objection, never the real one. Welcoming it kills the adversarial dynamic and surfaces the true reason underneath. Now listen to elite: When a buyer pushes back, my first move is to thank them for it — out loud. "Honestly, I appreciate you saying that. Most people would have just ghosted me. Tell me more about where that's coming from." That single beat does more than any rebuttal: it kills the adversarial dynamic and makes the prospect comfortable telling me the real reason — which is almost never the first one they said.$ds$,
  drill_ready = true
WHERE concept_id = 'OBF01' AND order_in_concept = 1;

UPDATE public.ki_curriculum SET
  drill_scenario = $sc$Marisol Vega, a senior manager at a national retailer, sends you weekly intel, shares your slides internally, and calls herself your "internal advocate." You've asked twice for a meeting with her VP of Digital — she's dodged both times. Is she a champion?$sc$,
  drill_spoken_task = $ts$Answer the concept question — champion or coach — and then say the exact test line you'd use with Marisol next week to prove it.$ts$,
  drill_model_answer = $ma$A coach gives you information. A champion spends political capital. I test it the same way every time: 'Would you be willing to set up a 20-minute working session with you, your boss, and me next week to align on next steps?' A coach hedges. A champion picks a day.$ma$,
  drill_rubric = '[{"c":"Classifies the contact as a coach — not a champion — given the pattern","must":true},{"c":"Names the specific test: asking her to spend political capital, e.g. setting up a meeting with her boss"},{"c":"Includes a concrete forward-motion ask, not just ''keep nurturing''"}]'::jsonb,
  drill_teach_script = $ds$The tactic: distinguish champions from coaches. A coach shares information and likes you. A champion spends political capital on you — brings peers into the room, pushes back on their own boss, defends the deal when you're not there. Use it any time a friendly contact hasn't yet introduced you to power, or before you rely on someone to carry your message into an internal decision meeting. Why it matters: pipeline dies on the coach-mistaken-for-champion problem. Test them before you bet the deal on them. Now listen to elite: A coach gives you information. A champion spends political capital. I test it the same way every time: 'Would you be willing to set up a 20-minute working session with you, your boss, and me next week to align on next steps?' A coach hedges. A champion picks a day.$ds$,
  drill_ready = true
WHERE concept_id = 'CHI01' AND order_in_concept = 1;
