UPDATE public.ki_curriculum SET
  drill_scenario = 'First-time discovery call with the VP of Product at a top-5 US retail app (500M+ MAUs, heavy paid-social spend). The invite was for 30 minutes. She joined 90 seconds late, camera on, and immediately types in chat: ''hard stop in 22 min — jumping to a board thing.'' You have not spoken yet. You know from her LinkedIn she is new in seat (six weeks). Open the call.',
  drill_model_answer = 'Hey, before we jump into this, I want to confirm you have about 20 minutes. My main goal here is to understand what prompted you to take this call and what you''re hoping to achieve. I''ll also assess if we''re a good fit and outline next steps accordingly. Does that work for you?',
  drill_rubric = '[{"c": "Confirms remaining time up front (about 20 minutes given her hard stop)", "must": true}, {"c": "States a purpose that includes understanding her goals / what prompted the call", "must": true}, {"c": "Names ''assess fit'' and ''outline next steps'' as call outputs", "must": true}, {"c": "Ends with an alignment ask that gives her a chance to redirect", "must": true}, {"c": "Does not launch into product pitch or company slides", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the move: an upfront contract. When an exec joins late with a hard stop, the worst thing you can do is start pitching or apologizing. Principle: alignment before content. You confirm the time, name the purpose in one breath, and end with a question that gives them permission to steer. The model line: ''Before we jump in, I want to confirm you have about twenty minutes. My goal is to understand what prompted this call and what you''re hoping to achieve. I''ll also assess if we''re a good fit and outline next steps. Does that work?'' Try it: exec on the line, twenty-two minutes, hasn''t said hello. Go.',
  drill_ready = true
WHERE concept_id = 'OPN05' AND ki_id = 'c41d134d-c728-46a5-b8bd-6a8f8954a53d';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Mid-discovery with the Mobile Growth Manager at a Big-3 US airline. She just walked you through how deep-link failures are dropping roughly 12-15% of email-to-app users on the homepage instead of the fare page during flash-sale pushes, costing them an estimated $2.1M last quarter. You summarized it back; she confirmed. She is the only name on the opp. You need to expand into loyalty and paid media before the next call. Ask the next question.',
  drill_model_answer = 'Can you help me understand who else in your organization feels the impact of these delays and how it affects their daily work? I want to ensure we address everyone''s concerns effectively.',
  drill_rubric = '[{"c": "Asks who else is impacted by the specific problem just summarized", "must": true}, {"c": "Frames the ask around impact on THEIR work (not around your sales process)", "must": true}, {"c": "Comes AFTER the problem has been established and summarized, not before", "must": true}, {"c": "Sets up a natural intro path (mentions addressing their concerns / bringing them in)", "must": false}]'::jsonb,
  drill_teach_script = 'Move: ''Who else is impacted?'' You just summarized a real business problem back to your contact and she agreed. That agreement is the doorway. Principle: stakeholder expansion feels organic when you anchor it to a problem the buyer already owns, not to your need to multi-thread. The line: ''Can you help me understand who else in your organization feels the impact of these delays and how it affects their daily work? I want to make sure we address everyone''s concerns effectively.'' Try it: growth manager just agreed the deep-link issue costs them two million a quarter. Ask.',
  drill_ready = true
WHERE concept_id = 'MSD01' AND ki_id = '2c90911f-8311-4682-b650-a100183063df';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Fintech deal, three weeks from close. Your champion (VP Growth) just emailed the group: ''Team''s stretched thin — probably not the right month to kick off. Let''s revisit in Q1.'' Ten minutes later, your champion pings you privately on Slack: ''I don''t think that''s the only thing going on — CFO has been quiet lately.'' You have a call with the VP in an hour. Handle the timing objection.',
  drill_model_answer = 'Before I solve anything, I want to make sure I''m solving the right thing. If we made the timing concern go away — let''s say we could push kickoff to January instead of next month — would that get this deal done? Or is there something else underneath that we haven''t put on the table? If they hesitate, the real objection is somewhere else, and I''d rather find it now than burn a week negotiating against the wrong problem.',
  drill_rubric = '[{"c": "Does NOT immediately try to solve the stated timing objection", "must": true}, {"c": "Uses an isolation move (hypothetically removes the timing objection to test if it is the real blocker)", "must": true}, {"c": "Explicitly invites disclosure of any other underlying concern", "must": true}, {"c": "Reads hesitation as a signal the real objection is elsewhere", "must": false}]'::jsonb,
  drill_teach_script = 'Move: isolate before you solve. When a champion says ''not the right month'' and hints something else is off, solving the timing gets you nothing — you''ll close the wrong door and the deal still stalls. Principle: hypothetically remove the stated objection and see if the deal actually moves. If they hesitate, there''s a second objection underneath. The line: ''If we made the timing concern go away — say we start in January instead of next month — would that get this deal done? Or is there something else underneath we haven''t put on the table?'' Try it: VP just said not this month. Your turn.',
  drill_ready = true
WHERE concept_id = 'OBF02' AND ki_id = '99784bbe-9b2a-4732-8662-228222bd9dfd';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Three-year Universal Ads expansion at a gaming publisher, verbal yes from your champion (VP Marketing) for two weeks. Final redline call just started; the CFO joined cold, no context, and opens with: ''The price is fifteen percent too high. Get it in range or we''re not signing this month.'' Champion is silent on camera. Respond to the CFO.',
  drill_model_answer = 'I hear you. Let me open up what the price actually reflects, because it''s four levers, not one number. This price reflects how much volume you committed to, how fast you pay, how long you commit, and when we sign. If you want to cut the price fifteen percent, we can — pick one. Drop the volume tier and unit cost goes up. Sign a one-year instead of three and we lose the multi-year discount. Pay quarterly instead of upfront and Finance has to reprice. Move the signature from this quarter to next and the discount schedule resets. Which one of those trades is the one you''d actually make?',
  drill_rubric = '[{"c": "Does not defend or apologize for the price number itself", "must": true}, {"c": "Names all four levers (volume, timing of payment, length of commitment, timing of the deal)", "must": true}, {"c": "Assigns a concrete trade to each lever so the CFO sees the give-to-get", "must": true}, {"c": "Ends by asking the CFO which trade they''d actually make", "must": true}, {"c": "Does not concede the 15% or promise a discount", "must": false}]'::jsonb,
  drill_teach_script = 'Move: deconstruct the price. When a CFO lands cold and slams the number, defending it loses. Principle: price is not a number, it''s four levers — volume, payment terms, commitment length, and signature timing. If they want to move the price, they pick a lever. The line: ''This price reflects four things — how much volume, how fast you pay, how long you commit, and when we sign. You want fifteen percent off? Pick one. Drop volume, unit cost goes up. Sign one year, we lose the multi-year discount. Which trade is the one you''d actually make?'' Try it: CFO just demanded fifteen percent off. Go.',
  drill_ready = true
WHERE concept_id = 'PRX01' AND ki_id = 'ac523270-c43b-4823-be23-d3e2ad950ded';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Discovery call with the CMO of a top-20 mobile gaming publisher. Four-year Adjust customer. They are launching a web-to-app funnel for a new franchise and doing serious deep linking for the first time. CMO leans in: ''Adjust has been fine for us — solid on network reporting. In one paragraph, tell me why we''d move any of this to Branch instead of just expanding Adjust.'' Respond.',
  drill_model_answer = 'When the incumbent comes up I lead with respect: Adjust is excellent at raw ad-network reporting — that''s why they own the performance-marketing crowd. Then I narrow the frame: for a company doing web-to-app and deep linking at your scale, here''s where their model bends and ours was built for it. Compliment, box, differentiate — in that order, in one breath.',
  drill_rubric = '[{"c": "Opens with a genuine compliment on Adjust''s real strength (ad-network reporting / performance marketing)", "must": true}, {"c": "Boxes Adjust into that specific niche rather than positioning them as broadly weaker", "must": true}, {"c": "Differentiates Branch specifically on web-to-app and deep linking at scale (matches the buyer''s stated need)", "must": true}, {"c": "Does not directly attack Adjust or call them bad", "must": false}]'::jsonb,
  drill_teach_script = 'Move: CBD — Compliment, Box, Differentiate. When a buyer names an incumbent they like, attacking loses and defending your product looks weak. Principle: acknowledge their strength honestly, then narrow the frame to where your product was purpose-built. The line: ''Adjust is excellent at raw ad-network reporting — that''s why they own the performance-marketing crowd. For a company doing web-to-app and deep linking at your scale, here''s where their model bends and ours was built for it.'' Compliment, box, differentiate — one breath. Try it: CMO just asked why they''d move deep linking off Adjust. Go.',
  drill_ready = true
WHERE concept_id = 'CDP01' AND ki_id = 'f83de6c6-f4d4-436e-87c4-663f7d0eaea7';

UPDATE public.ki_curriculum SET
  drill_scenario = 'A top-10 streaming media SVP asks you for a one-paragraph value summary before her Finance review tomorrow. You know the numbers: 18% of company revenue is app-attributable, ARPU is $4.20, they have 90M installs, web-to-app broken links cost them roughly 4.1M sessions/quarter, and the CFO is openly skeptical of adtech ROI. Write the value claim she can walk into that Finance meeting with.',
  drill_model_answer = 'Every value claim I make ties back to one of four numbers your CFO already tracks: revenue up, cost down, capital tied up reduced, or risk avoided. For you, it''s revenue up: 4.1M lost app sessions per quarter times an ARPU of $4.20 is roughly $17M/quarter of recoverable revenue on 18% of company sales — I''ve named the category, I''ve attached the math, I''ve sourced the math from your data, and your finance team can check my work. Vague ROI dies in finance — specific ROI passes.',
  drill_rubric = '[{"c": "Names one of the four CFO categories explicitly (revenue up / cost down / capital reduced / risk avoided)", "must": true}, {"c": "Attaches concrete math using THEIR numbers (sessions, ARPU, revenue share)", "must": true}, {"c": "Sources the math from the buyer''s own data, not vendor benchmarks", "must": true}, {"c": "Invites the finance team to check the math (transparency)", "must": false}]'::jsonb,
  drill_teach_script = 'Move: quantify in the CFO''s four categories. When an exec is heading into a finance review, vague value claims get shredded. Principle: every value claim ties to one of four numbers a CFO already tracks — revenue up, cost down, capital reduced, risk avoided. Name the category, attach the math, source it from their data. The line: ''Revenue up — 4.1 million lost sessions a quarter times an ARPU of four-twenty is about seventeen million quarterly of recoverable revenue, on the eighteen percent of sales that''s app-attributable. Your finance team can check my work.'' Try it: SVP needs a value paragraph for tomorrow''s finance meeting. Write it.',
  drill_ready = true
WHERE concept_id = 'VPR04' AND ki_id = 'b53de861-850a-4e2a-9680-eb22d3df844f';

UPDATE public.ki_curriculum SET
  drill_scenario = 'You''re the AE on a Tier-1 travel account. Renewal is 90 days out; Branch is the incumbent. A new CMO started six weeks ago and has requested a ''Branch overview'' — she has not decided anything is broken yet and has no urgency around the renewal. Your instinct is to walk in with the roadmap deck. Structure how you''d actually run the first meeting.',
  drill_model_answer = 'I run every cycle in this order: Why change, Why now, Why us — and not before. If I lead with Why us, I''m pitching to people who haven''t decided they need to do anything. So early calls I''m only working the first two; product comes last, and only after the urgency is real. In this meeting that means I skip the roadmap deck, spend the first half surfacing what''s changed in her world since she took the seat, then in the second half connect the cost of not addressing it to her ninety-day plan. Branch''s fit comes on the next call, not this one.',
  drill_rubric = '[{"c": "Names the ordering explicitly: Why change → Why now → Why us", "must": true}, {"c": "Explicitly refuses to lead with Why us / the roadmap or product in this first meeting", "must": true}, {"c": "Uses the meeting to develop Why change and Why now first", "must": true}, {"c": "Defers Why us / Branch fit to a later call, after urgency is established", "must": false}]'::jsonb,
  drill_teach_script = 'Move: sequence Why change, Why now, Why us — in that order. New CMO with no urgency and you walk in with a roadmap deck? You just pitched a solution to someone who hasn''t decided there''s a problem. Principle: buyers resist change by default. Product last, urgency first. The line: ''I run every cycle in this order — Why change, Why now, Why us. If I lead with Why us, I''m pitching to people who haven''t decided they need to do anything.'' Try it: new CMO asked for a Branch overview. Renewal in ninety days. Structure the first meeting.',
  drill_ready = true
WHERE concept_id = 'WHY01' AND ki_id = '916c02e9-d48f-4c55-a5ae-e9ffee6d1714';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Two back-to-back meetings tomorrow at a Tier-1 US retailer. 9am: 45 minutes with the CFO. 2pm: 30 minutes with the Director of Mobile Growth who reports two levels below her. Same underlying problem in both rooms: 22% of their paid-social-to-app traffic drops at the app store handoff, dragging ROAS down roughly 30% on a $40M annual mobile ad spend. How do you frame the problem for each stakeholder?',
  drill_model_answer = 'I rewrite the same problem twice before any exec meeting — once in process language for the manager, once in P&L and strategic-outcome language for the C-suite. With the CFO tomorrow I''m talking margin compression on the mobile ad spend, working capital tied up in wasted media, and risk exposure on the paid-social channel — roughly twelve million a year of underperforming spend. With the director in the afternoon I''m talking handoffs at the app-store step, cycle time on deep-link fixes, and the rework her team eats every campaign. Same problem, different altitude.',
  drill_rubric = '[{"c": "Explicitly rewrites the SAME problem twice — one version per stakeholder", "must": true}, {"c": "CFO framing uses P&L / financial / strategic-outcome language (margin, working capital, risk, or dollar exposure)", "must": true}, {"c": "Director framing uses process-level language (handoffs, cycle time, rework, or similar operational terms)", "must": true}, {"c": "Does not use identical language for both audiences", "must": true}]'::jsonb,
  drill_teach_script = 'Move: calibrate the problem to their altitude. Same problem, two rooms, one AE — and the wrong instinct is to reuse the deck. Principle: managers live in process; executives live in P&L. If you speak process to the CFO, you sound tactical. If you speak P&L to the manager, you sound abstract. The line: ''I rewrite the same problem twice before any exec meeting — once in process language for the manager, once in P&L and strategic-outcome language for the C-suite.'' Try it: CFO in the morning, Director in the afternoon, same twenty-two-percent app-store drop. Frame it for each.',
  drill_ready = true
WHERE concept_id = 'CXA01' AND ki_id = '7e0659ec-e1b3-45dd-99e1-04aabf596eb5';