-- Batch 8: 8 elite drill packages (stakeholder_navigation b2)
-- Self-verified via dojo-score 3x; all median>=92, all musts met 3/3.

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re the Branch strategic AE on a media & entertainment expansion play at a top-5 streaming service. Your day-to-day contact is the Director of Mobile Growth. On today''s call she wraps by saying: ''I actually think the right person for you to talk to next is Priya, our VP of Growth — she owns the whole retention P&L and she''s been asking questions about our attribution stack.'' Before you say ''great, please intro us,'' capture the intel. You have about fifteen seconds.',
  drill_spoken_task  = 'Ask your current contact the one question that turns this referral into a meeting where your first sentence lands on Priya''s actual priority. Give the whole ask, in your natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'Right after a referral, I ask my current contact: ''When I sit down with your VP of Growth, what are the two or three things she cares most about right now?'' That one question turns a cold intro into a meeting where my first sentence already lands on her priority.',
  drill_rubric       = '[{"c": "Asks the current contact what the referred senior stakeholder cares most about (top priorities / concerns), by name or role", "must": true}, {"c": "Frames the ask as prep for the upcoming meeting with the senior stakeholder (not generic curiosity)", "must": true}, {"c": "Names why it matters \u2014 so the first sentence with the exec lands on her real priority, turning a cold intro warm", "must": false}, {"c": "Delivered as one tight ask the current contact would actually answer (not a multi-part interrogation)", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Ask What Each Stakeholder Cares About. Beat one: the moment. Your contact just offered a referral to someone senior. Beat two: the tactic. Before the intro goes out, ask what the referred exec cares most about right now. Beat three: why it works. You walk into that next meeting already speaking to her priorities, not your product. Beat four: the ask. Try it: ''When I sit down with your VP, what are the two or three things she cares most about?''',
  drill_ready        = true
WHERE concept_id = 'BON01' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re pitching Universal Ads expansion to a retail brand — a household name in outdoor gear. You''re in a value-review call with your day-one champion, the Head of Performance Marketing. Pricing lands next Tuesday. You already know from side conversations that anything over 250K at this company pulls in Security, Finance, and the mobile platform team. Your champion has NOT yet acknowledged those stakeholders exist. If you show pricing without locking who else weighs in, this deal slips a quarter.',
  drill_spoken_task  = 'Before you get to price, surface the full mobilizer list and lock your champion into bringing them into a working session if the value case holds. One flow, in your own voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I get the mobilizer list on the table before I show a price. ''In your world, when something at this dollar amount moves forward, who else weighs in — security, finance, the platform team?'' Then I lock it: ''If we agree the value''s there next week, are you good bringing those three into a working session, or do I need to earn that?''',
  drill_rubric       = '[{"c": "Surfaces the full mobilizer list explicitly \u2014 asks who else weighs in at this dollar amount (names roles like security / finance / platform / IT)", "must": true}, {"c": "Secures a conditional commitment: IF value holds, THEN champion brings those stakeholders into a working session", "must": true}, {"c": "Sequences the ask BEFORE price is shown, not after", "must": false}, {"c": "Gives the champion a graceful out (''or do I need to earn that'') so it reads as a real ask, not a demand", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Lock Mobilizers via Upfront Agreements. Beat one: the moment. You''re days from pricing and only your champion is in the room. Beat two: the tactic. Before price hits the table, surface every mobilizer — security, finance, platform, whoever weighs in at this size. Beat three: the lock. Tie their involvement to value: if the value holds next week, will you bring them into a working session? Beat four: why it works. You''re not asking for a favor at the end. You''re building the path now, when your champion still has momentum.',
  drill_ready        = true
WHERE concept_id = 'CHB02' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re at a fintech app — a top-ten challenger bank — pitching Branch''s Advanced Privacy suite as part of a footprint expansion. Your champion is the Director of Mobile Product. She has to walk a one-page business case into her CFO in ten days. Your instinct is to draft it clean, send it over, and ask her to ''review.'' You know that ends with silence for a week and no CFO buy-in. You''re on a working session now.',
  drill_spoken_task  = 'Set the co-authoring frame with your champion — right now, out loud — so the business case has her fingerprints, not just your polish. Give the whole thing in your natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I tell the champion up front: ''I''m not going to write this and send it to you for review — that always gets ignored. I''m going to share a doc, you tell me what your CFO actually cares about, and we''ll shape it together.'' Their fingerprints on the doc means their political capital is on the doc.',
  drill_rubric       = '[{"c": "Explicitly rejects the ''I write, you review'' pattern and names why it fails (gets ignored / silence)", "must": true}, {"c": "Proposes a co-authoring model: shared doc, champion supplies what the CFO actually cares about, shaped together", "must": true}, {"c": "Ties the co-authoring behavior to political capital / champion ownership of the final doc", "must": false}, {"c": "Delivered peer-to-peer, not as a favor request", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Co-Author the Business Case. Beat one: the moment. Your champion has to walk a business case into her CFO and you''re about to draft it. Beat two: the trap. If you write it and send it for review, it dies in her inbox. Beat three: the tactic. Frame it as co-authoring — you share a doc, she tells you what her CFO actually cares about, and you shape it together. Beat four: why it works. Her fingerprints on the doc means her political capital is on the doc. She''ll fight for it inside because she wrote it.',
  drill_ready        = true
WHERE concept_id = 'CHE02' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re the Branch AE on a travel account — a global online travel platform expanding Email-to-App. Your contact, a Senior Manager on the CRM team, has been enthusiastic on every call for six weeks. You''ve never met her boss. You don''t have a single written artifact from her side. Next week is a critical exec review and you''re not sure whether she''s a real champion or just a friendly coach. You need to test — this week — with two small asks.',
  drill_spoken_task  = 'Talk through the two small asks you''d run this week to test whether she''s a real champion, plus what you conclude and do next if she goes silent. Natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I run small asks to see who''s real. ''Can you forward me the email thread where your VP raised this last quarter?'' or ''What''s your boss going to push back on first?'' If they share, they''re invested. If they go quiet for a week, I have a coach, not a champion, and I need to multi-thread now.',
  drill_rubric       = '[{"c": "Names at least one concrete small ask that requires internal sharing or preview of the boss''s thinking (e.g. forward the thread, tell me what your boss will push back on)", "must": true}, {"c": "States the read: sharing = real champion / invested; silence = coach only", "must": true}, {"c": "Names the corrective action when the test fails \u2014 start multi-threading now, don''t keep coasting on the coach", "must": true}, {"c": "Frames it as a repeatable test, not a one-off gut check", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Test the Champion via Willingness to Collaborate. Beat one: the moment. Someone''s enthusiastic on your calls but you have no idea if they''ll spend political capital for you. Beat two: the test. Run small asks that only a real champion would say yes to — forward me the exec''s thread, tell me what your boss will push back on first. Beat three: read the signal. If they share, they''re invested. If they go quiet for a week, you have a coach, not a champion. Beat four: what to do about it. When the test fails, don''t hope — multi-thread now, this week, before the exec review.',
  drill_ready        = true
WHERE concept_id = 'CHI02' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re on a first call with the CFO of a top-tier fintech — a payments platform. Your champion opened the door. The CFO gave you thirty minutes. You know the failure mode: you''ll be tempted to demo Branch features, walk him through the platform, prove technical depth. That''s the fastest way to lose the room. He''ll drop into ''how does it integrate with our data warehouse'' and you''ll spend twenty minutes there.',
  drill_spoken_task  = 'Open the call as a peer, and describe how you''ll hold that altitude if he tries to drag you into tactics. Whole thing, natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I don''t ''pitch up'' to a CFO. I open with a peer-level frame: ''Most CFOs I work with at your stage are weighing X against Y — which one is on your desk this quarter?'' Then I hold strategic, not tactical. No demo, no feature talk. If I get dragged into ''how does it integrate,'' I redirect: ''happy to put your platform lead on with mine — what I''d love your read on is...''',
  drill_rubric       = '[{"c": "Opens with a peer-level strategic frame \u2014 references what CFOs at this stage typically weigh, and asks which is on his desk (not a features intro)", "must": true}, {"c": "Explicitly holds strategic altitude \u2014 no demo, no feature walkthrough", "must": true}, {"c": "Names the redirect move when he pulls toward tactics \u2014 hand technical questions to a platform / SE peer and pull the CFO back to a strategic question", "must": true}, {"c": "Tone reads confident and peer-level, not deferential (''pitching up'') or pandering", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Engage as a Peer, Not a Subordinate. Beat one: the moment. Thirty minutes with a CFO and every instinct says prove yourself with features. Beat two: don''t. Open peer-level: ''Most CFOs at your stage are weighing X against Y — which one is on your desk this quarter?'' Beat three: hold altitude. No demo, no feature talk, no scrambling. Beat four: the redirect. When he drags you into ''how does it integrate,'' say ''happy to put your platform lead on with mine'' and pull him back to the strategic question you actually came for.',
  drill_ready        = true
WHERE concept_id = 'CSP01' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re the Branch expansion AE on a gaming account — a major mobile-first publisher. Their SVP of Growth reached out cold on LinkedIn after seeing a Branch case study, and you have a first meeting with her booked for Thursday. Your rep instinct is to run standard discovery on data taxonomy, current attribution setup, and MMP contracts. That''s the fastest way to burn this. She''s an exec, she came to you first, and she''ll disengage if you treat her like a champion you need to develop.',
  drill_spoken_task  = 'Describe how you''ll run this first meeting — what altitude you''ll hold, what you will NOT do, and how you get the right operator on the deal without pushing her away. Natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'If the exec is who reached out first, I don''t push them down to the IC. I run discovery at their altitude — strategic priorities, board narrative, what ''good'' looks like in 12 months — and then ask: ''Who on your team should I work with day-to-day so we''re not eating your calendar?'' The exec stays the sponsor, the IC becomes the operator.',
  drill_rubric       = '[{"c": "Runs discovery at exec altitude \u2014 strategic priorities, board narrative, 12-month ''good'' \u2014 not tactical/technical discovery on taxonomy, attribution, MMP, etc.", "must": true}, {"c": "Explicitly does NOT push the exec down to an IC or treat her like a champion to develop", "must": true}, {"c": "Asks the exec who on her team the seller should work with day-to-day (frames as respecting her calendar) \u2014 sponsor + operator split", "must": true}, {"c": "Names the sponsor / operator model or equivalent role split so the exec stays engaged at the top", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Start Discovery at Power. Beat one: the moment. An exec reached out to you first. That means the whole cycle inverts. Beat two: don''t demote her. Do NOT drop into tactical discovery and do NOT push her down to an IC. Beat three: hold altitude. Ask about strategic priorities, the board narrative, what ''good'' looks like in 12 months. Beat four: the split. Then ask ''who on your team should I work with day-to-day so we''re not eating your calendar?'' The exec stays the sponsor. The IC becomes the operator. You keep the top of the house and gain the bottom.',
  drill_ready        = true
WHERE concept_id = 'EXE01' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re the Branch strategic AE on a 900K expansion at a global retail brand. Their buying group is fifteen people across mobile engineering, martech, procurement, and finance. You''ve been running the deal solo for three weeks and it''s showing — the CTO wants technical depth you can''t give in the room, the CFO wants peer-level cover, and CS is nowhere in the conversation. Your Sales VP just asked you ''who else from our side is on this deal?'' Right now the answer is nobody.',
  drill_spoken_task  = 'Walk through how you''re going to build and brief your internal selling team for this deal — who you pull in, why, and what each of them owns going in. Natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'On any deal over a few hundred K I sit down and name the people I need on my side of the table — an SE for the technical stakeholder, CS for implementation questions, my VP for peer cover, sometimes our CEO. Then I brief each of them on what the buyer actually cares about, not just ''come to the call.''',
  drill_rubric       = '[{"c": "Explicitly assembles a named internal team mapped to buyer stakeholders \u2014 SE for technical, CS for implementation, sales leader for peer cover (plus CEO where warranted)", "must": true}, {"c": "Ties each internal role to a specific buyer-side concern, not generic ''come to the call''", "must": true}, {"c": "Names the briefing step \u2014 each internal team member is prepped on what the buyer actually cares about before the meeting", "must": true}, {"c": "Treats this as the standard operating move for deals of this size, not a one-off scramble", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Orchestrate an Internal Selling Team. Beat one: the moment. A big deal, a wide buying committee, and it''s just you on your side of the table. Beat two: name the team. On any deal at this size you need an SE for the technical stakeholder, CS for implementation, your VP for peer cover, sometimes your CEO. Beat three: match each seat. Every internal person maps to a specific buyer-side concern — don''t just fill chairs. Beat four: brief them. Each teammate walks in knowing what the buyer actually cares about, not ''hey come to a call.''',
  drill_ready        = true
WHERE concept_id = 'IDT02' AND is_exemplar = true;

UPDATE public.ki_curriculum SET
  drill_scenario     = 'You''re twelve weeks into a strategic expansion at a global travel platform. Your champion is the Director of Mobile Growth and every stakeholder you''ve met came from her. LinkedIn shows a brand-new VP of Data joined six weeks ago from a company that ran Branch heavily, an engineering director who''s been tweeting about deferred deep linking pain, and an FP&A lead whose name is on the last QBR deck. Your champion has never mentioned any of them. You''re not going to wait for permission — but you''re also not going to breach trust.',
  drill_spoken_task  = 'Talk through how you''ll multi-thread beyond your champion this week — who you''ll research, and how you loop your champion in without breaking trust. Natural voice.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I don''t let the champion be my org chart. I''ll go research the new VP who joined six weeks ago, the engineering director who tweeted about this exact problem, the FP&A lead whose name showed up on the QBR deck. Then I bring those names back to my champion: ''Should we get any of them in the room?''',
  drill_rubric       = '[{"c": "Refuses to let the champion be the sole org chart \u2014 proactively identifies stakeholders the champion has NOT mentioned (new hires, public signals, exec names in artifacts)", "must": true}, {"c": "Names at least two concrete outside-of-champion targets with WHY (new VP, engineering director tweeting about the problem, FP&A lead on the QBR deck, or equivalent specifics)", "must": true}, {"c": "Loops the champion back in on the outreach (''should we get any of them in the room?'') to preserve trust \u2014 not stealth around them", "must": true}, {"c": "Treats this as continuous prospecting inside the account, not a one-off panic move", "must": false}]'::jsonb,
  drill_teach_script = 'Here''s the play — Multi-Thread Beyond the Champion. Beat one: the moment. Twelve weeks in, every contact came from your champion. That''s a single point of failure. Beat two: go find the others. Research the new VP who joined six weeks ago, the engineering director tweeting about the problem, the FP&A lead on the QBR deck. Beat three: don''t stealth around your champion. Bring those names back to her — ''should we get any of them in the room?'' Beat four: why it works. You expand reach without breaking trust, and you build the deal on more than one relationship.',
  drill_ready        = true
WHERE concept_id = 'MTH03' AND is_exemplar = true;
