
ALTER TABLE public.ki_curriculum
  ADD COLUMN IF NOT EXISTS drill_teach_script text;

UPDATE public.ki_curriculum kc
SET drill_teach_script = v.script
FROM (VALUES
  ('CRC04', $$The tactic: you plant three specific criteria in the buyer's head before the bake-off — three things you know you win on, framed as what any serious vendor should be judged on. Use it early, while the buyer is still shaping their evaluation plan and hasn't locked competitors in. Why it matters: whoever writes the rubric wins the deal. Your buyer walks into the competitor's demo already scoring on your criteria, and the competitor either can't meet them or bluffs. Now listen to elite: Before the bake-off I plant the flag: 'Three things will decide whether this works for you — deferred deep linking, web-to-app conversion, and attribution that survives iOS 17. Watch every vendor on those.' I picked those three because I win all three. When the buyer walks into the competitor's demo, they're already scoring it on my rubric.$$),
  ('ERX02', $$The tactic: don't wait for renewal signals. Watch three things — how deep senior leaders use the product, whether your API is wired into their other systems, and one open question you ask them: 'what do you wish this did that it doesn't?' Use it continuously on every managed account, especially ones with big footprint or a shaky rollout. Why it matters: lagging indicators tell you it's already over. Leading indicators tell you what to fix while you still can, and where the next expansion actually lives. Now listen to elite: If there's an open wound from the original deployment, I refuse to talk expansion until it's closed. I'll say it out loud to the exec: 'Before I bring you a bigger idea, I owe you a clean rollout on what you already paid for — here's what I'm going to fix in the next 30 days, and I'll come back to you when it's done.' That sequence is what makes them lean in when I do come back.$$),
  ('EXM03', $$The tactic: when you write the headline for an exec business case, use their internal words and their internal metrics — the phrase their VP would actually say in a Monday QBR, and a number they already track. Not your product name. Not industry buzzwords. Their language. Use it every time you send an exec-facing doc, deck, or one-pager. Why it matters: execs filter in seconds. If the first line sounds like a vendor pitch, they skim. If it sounds like their own team wrote it about their own problem, they read. Now listen to elite: I never pitch the exec on what the product does. I pitch them on what their VP of Growth stops having to apologize for in the Monday QBR. "Your performance team gets back the four hours a week they currently spend reconciling MMP numbers, and the attribution dispute with finance goes away." The exec buys their team's relief, not my feature.$$),
  ('GTK04', $$The tactic: when a stakeholder blocks you with 'we've got it covered, no need to talk,' signal you're operating one level above them by name-dropping a senior person who asked for them by name. Not gratuitous — specific: who asked, what forum, why they want this person in the room. Use it when a mid-level owner tries to shut the door and you have a real senior stakeholder — a CFO, a VP — who legitimately wants the meeting. Why it matters: 'we got this' is a status play. Answering with a bigger status — a room they weren't invited to yet — flips the ask from optional to unmissable, without you sounding pushy. Now listen to elite: When a team says 'we've got it covered, don't need to talk,' I drop names — not gratuitously, but to signal I'm operating at the level above them: 'Totally hear you. The reason I'm reaching out is the CFO's office has been pushing a working group on this and your name came up as someone they wanted in the room.' Suddenly 'we got this' becomes 'oh, let me set up time.'$$),
  ('ID06', $$The tactic: when security or IT raises authentication, answer with specifics — Branch supports SAML 2.0 with Okta, Azure AD, OneLogin, and any SAML-compliant IDP. Setup takes about an hour and IT does most of it. Then point them at the step-by-step guide in Account Hub. Use it the moment a prospect raises SSO, security review, or user provisioning — usually late in enterprise procurement. Why it matters: SSO is a checklist item that stalls deals when it's vague and closes them fast when it's crisp. Naming the IDPs and the setup time removes the unknown legal and IT are waiting on. Now listen to elite: Branch supports SAML 2.0 SSO compatible with Okta, Azure AD (Entra ID), OneLogin, and any SAML-compliant IDP. Once configured, all dashboard users authenticate through the company's identity provider — no Branch-specific passwords, automatic deprovisioning when someone leaves the company. SSO is an IT and security requirement that surfaces late in enterprise procurement as a checklist item. Setup takes about an hour: export Branch's service provider metadata, configure a SAML app in the customer's IDP, map the attribute fields, test. The customer's IT team does most of the IDP-side configuration. Branch documentation has step-by-step guides for the major IDPs.$$),
  ('PRC02', $$The tactic: always present three pricing options, never one. Anchor high on the top option, make the low option obviously worse on one specific tradeoff, and position the middle as what most customers choose. You're not negotiating a number — you're setting a menu the buyer picks from. Use it any time you're quoting price, term length, or scope — especially in renewals and expansion. Why it matters: one number gets negotiated down. Three options flip the buyer's brain from 'how low will they go?' to 'which one is right for us?' — and the middle almost always wins. Now listen to elite: Three options, always. 'Most customers choose middle. The high option is for teams who want X; the low option is for teams comfortable trading off Y.' The middle becomes the obvious choice and the anchor is set higher than any single number I'd have led with.$$),
  ('PRV01', $$The tactic: watch for the physical moment an objection forms — the buyer goes quiet, looks away, shifts in their seat — and stop the pitch right there. Name what you saw, soft tone: 'you got quieter on that integration slide — what's that about?' Use it live, the second you see the cue — not later, not in follow-up. Why it matters: a forming objection takes thirty seconds to surface. A hardened one becomes 'let me think about it' and costs you the deal. Now listen to elite: I watch for the moment the buyer goes quiet, looks away from camera, or shifts in their seat — and I stop the pitch right there. "Hey, you just got a little quieter when I went through that integration slide. What's that about?" Soft tone, no defensiveness. Catching an objection at the moment it's forming costs me 30 seconds. Letting it harden into "let me think about it" costs me the deal.$$),
  ('QFW01', $$The tactic: a real buyer shows three things — a clear problem, real understanding of what it costs to not fix it, and willingness to change how they work. Miss one and you've got a prospect, not a buyer. Ask two questions: 'what happens if this isn't solved in six months?' and 'what would you have to do internally to make this happen?' Use it throughout discovery, before you invest real time in a proposal. Why it matters: deals with all three close. Deals missing one become 'no decision' — the silent killer of your quota. Now listen to elite: I stopped opening with budget/authority/need/timing — modern buyers don't have any of those cleanly defined yet. Instead I ask: "Walk me through how a decision like this actually gets made here — who weighs in, what would have to be true." That tells me where I am in their process, not mine.$$)
) AS v(concept_id, script)
WHERE kc.concept_id = v.concept_id
  AND kc.drill_ready = true;
