
-- Daily time block plans generated by AI
CREATE TABLE public.daily_time_blocks (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  plan_date DATE NOT NULL,
  blocks JSONB NOT NULL DEFAULT '[]'::jsonb,
  meeting_load_hours NUMERIC DEFAULT 0,
  focus_hours_available NUMERIC DEFAULT 0,
  ai_reasoning TEXT,
  feedback_rating INTEGER, -- 1-5 stars
  feedback_text TEXT,
  feedback_submitted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(user_id, plan_date)
);

ALTER TABLE public.daily_time_blocks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own time blocks" ON public.daily_time_blocks FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own time blocks" ON public.daily_time_blocks FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own time blocks" ON public.daily_time_blocks FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own time blocks" ON public.daily_time_blocks FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- AI feedback table for general suggestions (reusable across features)
CREATE TABLE public.ai_feedback (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  feature TEXT NOT NULL, -- 'time_blocks', 'account_prioritizer', 'deal_strategy', etc.
  context_date DATE,
  rating INTEGER, -- 1-5
  feedback_text TEXT,
  ai_suggestion_summary TEXT, -- what the AI suggested
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.ai_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own feedback" ON public.ai_feedback FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own feedback" ON public.ai_feedback FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
