-- Batch 9 drill packages (self-verified, median 89-94, musts 3/3 all)

UPDATE public.ki_curriculum SET
  drill_scenario = 'StreamNest, a $600M CTV streaming operator. You''re in a 30-min working session with Priya Raman, a first-time CFO who was promoted from VP Finance 4 months ago. She''s already verbally sold on Branch Universal Ads for their CTV attribution problem — $2.3M ACV, target signature end of Q3 (7 weeks out). It''s a first-time CFO on a first-time enterprise mar-tech evaluation. She just said, ''Yeah, I''m bought in — send me the paper and we''ll get it done.'' You need to control for first-time-EB risk before you leave this call.',
  drill_spoken_task = 'Priya just said ''send me the paper.'' You know first-time EBs at this size stall on internal ownership. Say your next line to Priya — get the internal owner named on this call.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'When I''m dealing with a first-time CRO or first-time CFO, I assume nothing about internal project ownership. I ask early: ''Who inside your org is going to own driving this across the finish line — and what''s their bandwidth?'' If they wave it off, I push: ''In my experience, the deals that stall out at companies your size are the ones where that owner wasn''t named on day one — let''s avoid that.''',
  drill_rubric = '[{"c": "Names the risk explicitly \u2014 first-time EB / no internal project owner named", "must": true}, {"c": "Asks WHO inside her org drives this to the finish line (owner question)", "must": true}, {"c": "Pushes on bandwidth or ''named on day one'' if she waves it off", "must": false}, {"c": "Doesn''t accept ''send me the paper'' as sufficient control", "must": true}]'::jsonb,
  drill_teach_script = 'First-time enterprise buyers — first-time CFO, first-time CRO — are your highest-risk deals even when they say they''re bought in. Because they''ve never actually shepherded an eight-figure vendor through their own org, they don''t know what breaks. Your move is to name the internal owner on the call, not the contract. Ask: who drives this across the finish line, and what''s their bandwidth. If they wave it off, push once — deals at this size stall when the owner isn''t named on day one.',
  drill_ready = true
WHERE concept_id = 'CXE01' AND ki_id = 'cdba402a-92ed-4ae0-86e3-9f56fb94632e';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Hopper, a $500M travel booking app. You have a 25-minute intro with the Chief Growth Officer, Marcus Ellery. Hopper''s last earnings call flagged ''international expansion into LATAM'' and ''CAC pressure on paid channels'' as the two priorities for the year. You''re expanding an existing Branch deep-linking footprint into Universal Ads for their paid social re-engagement. Marcus opens with, ''So — walk me through Branch.''',
  drill_spoken_task = 'Marcus just said ''walk me through Branch.'' Do NOT walk him through the product. Open at exec altitude — tie your first sentence to what he''s already accountable for.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I open exec conversations on their strategic plate, not my product. I''ll quote a line from their last 10-K or earnings call — ''You called out international expansion and margin pressure on the Q3 call'' — and tie our work to that initiative. Managers get the pain story; executives get ''here''s how this moves the number you''re already accountable for.''',
  drill_rubric = '[{"c": "Opens on HIS strategic plate, not the product feature list", "must": true}, {"c": "Cites the specific earnings/10-K signal (LATAM expansion or CAC pressure)", "must": true}, {"c": "Ties Branch work to a number HE is already accountable for", "must": true}, {"c": "Explicitly avoids the manager-level pain-story register", "must": false}]'::jsonb,
  drill_teach_script = 'Executives don''t buy product tours — they buy movement on numbers they already own. Before you open your mouth in an exec meeting, name the two or three things on their strategic plate — from the last earnings call, the 10-K, the analyst deck. Then open by quoting one of them back. Tie your work to that initiative in the first sentence. Managers get the pain story; execs get the number.',
  drill_ready = true
WHERE concept_id = 'CXA02' AND ki_id = '7bd103cf-ca62-4aff-be54-85bc5566bb92';

UPDATE public.ki_curriculum SET
  drill_scenario = 'You run the Branch expansion team covering 14 enterprise accounts. Last quarter you went 4-and-3 in competitive deals against AppsFlyer and Adjust — 2 clean wins, 2 clean losses, 3 muddy. Your manager just asked in the QBR, ''What are we doing with this competitive data?'' Right now: nothing structured. Reps close a deal, celebrate, move on. Lose one, blame pricing, move on. You need to describe the operating cadence you''ll install this quarter.',
  drill_spoken_task = 'Your manager asked what you''re doing with the competitive data. Describe the cadence — how you''ll turn win/loss into rep behavior change, not a slide.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I run a 20-minute win/loss debrief on every competitive deal — won or lost — and I make the rep narrate the actual story: what the buyer believed coming in, what we changed, where the competitor hit us. Then I pull two specific moves from that into next week''s deal reviews. Intel only matters if it changes how the next rep plays.',
  drill_rubric = '[{"c": "Concrete cadence \u2014 every competitive deal, both wins AND losses, timeboxed debrief", "must": true}, {"c": "Rep narrates the buyer story (what they believed, what changed, where competitor hit)", "must": true}, {"c": "Feeds SPECIFIC moves into next week''s deal reviews \u2014 not a shelf-ware slide", "must": true}, {"c": "Explicit ''intel only matters if it changes behavior'' framing", "must": false}]'::jsonb,
  drill_teach_script = 'Most teams treat win/loss as a report — it should be a rep-behavior loop. Every competitive deal, won or lost, gets a twenty-minute debrief where the rep narrates the buyer story: what they believed coming in, what you changed, where the competitor hit you. Then you pull two specific moves from that debrief into next week''s deal reviews. If your competitive intel isn''t changing how the next rep plays the next deal, it''s decoration.',
  drill_ready = true
WHERE concept_id = 'CIN01' AND ki_id = 'a86f0dbd-d31b-4236-be30-5dd9a976945c';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Pulsefield, a $1.2B gaming publisher. Early-stage evaluation for Branch Universal Ads + deep linking, competing against Adjust incumbent. Deal is $1.8M ACV, Q4 close. You get to shape the eval before RFP writes itself. You know cleanly you beat Adjust on three things: Universal Ads cross-channel unification, Web-to-App with server-side attribution, and enterprise-grade fraud protection. First discovery call with the VP User Acquisition tomorrow morning.',
  drill_spoken_task = 'Walk me through the winning-zone move you''re making before tomorrow''s discovery call and during it — how you plan the eval to sit on your ground.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'Before the deal heats up I pick three areas I beat any competitor on cleanly — and I run discovery hard to find out whether those three things actually matter to this buyer. If they do, I anchor the whole evaluation on them. If they don''t, my job in the next call is to teach the buyer why they should.',
  drill_rubric = '[{"c": "Names the three winning-zone areas BEFORE the call (pre-selected, not improvised)", "must": true}, {"c": "Uses discovery to test whether those three matter to THIS buyer", "must": true}, {"c": "Two-branch logic: if they matter \u2192 anchor eval; if not \u2192 teach why they should", "must": true}, {"c": "Explicitly places move BEFORE the deal heats up / RFP writes itself", "must": false}]'::jsonb,
  drill_teach_script = 'Every competitive deal has three zones — where you win cleanly, where it''s neutral, and where you lose. Your job before the deal heats up is to pick your three winning areas and run discovery hard to see if they matter to this buyer. If they do, anchor the whole evaluation on them. If they don''t, your next call is a teaching call — you show the buyer why those three things should matter. You never let the evaluation get built on someone else''s ground.',
  drill_ready = true
WHERE concept_id = 'CWZ01' AND ki_id = 'c87b21dd-8ca5-433d-8286-0e817ac03eb7';

UPDATE public.ki_curriculum SET
  drill_scenario = 'Zestly Retail, $2.8B fashion e-commerce. You''re presenting the business case for a $1.4M Branch expansion — Email-to-App and Web-to-App attribution — to the CFO, CMO, and their heads of eng. Your SE built a beautiful 22-slide deck: slide 1 is a Branch SDK architecture diagram. The CFO''s calendar shows a hard stop at 30 minutes. Your champion pings you the night before: ''They''re going to skip past the tech stuff — what are you leading with?''',
  drill_spoken_task = 'Your champion just asked what you''re leading with tomorrow. Say your answer — the exec-facing sequencing rule and what slide one becomes.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'Lead with what the business gets, not what the product does. The first slide is the dollar outcome and the date; integration architecture lives in the appendix. Execs decide on impact and time-to-value — everything else is supporting evidence.',
  drill_rubric = '[{"c": "Explicitly reorders \u2014 business impact first, product/architecture demoted", "must": true}, {"c": "Slide 1 = dollar outcome AND date (or time-to-value)", "must": true}, {"c": "Integration/architecture moved to appendix (or explicitly deprioritized)", "must": true}, {"c": "Frames execs as impact + time-to-value decision-makers, not tech evaluators", "must": false}]'::jsonb,
  drill_teach_script = 'Executives don''t buy how it works — they buy what it produces and when. Your first slide is the dollar outcome and the date it lands. Architecture, integration, SDK diagrams — those go in the appendix. If the CFO asks a technical question you can flip to it, but you never lead with it. Lead with impact and time-to-value; everything else is supporting evidence for a decision they''ve already framed in dollars.',
  drill_ready = true
WHERE concept_id = 'BIZ03' AND ki_id = '88aef7f1-6424-4241-abf5-898060c6629c';

UPDATE public.ki_curriculum SET
  drill_scenario = 'FinNest, a $900M consumer fintech. You''re on a late-stage call — week 11 of 14 in the sales cycle, $1.6M ACV, four stakeholders on the line, verbal from the VP Growth two weeks ago. Legal review is ''in progress,'' security review is ''starting soon,'' and the champion just said ''we''re all aligned, we''ll get this over the line.'' Your gut says the deal is softer than the room sounds. You''ve got seven minutes left.',
  drill_spoken_task = 'You have seven minutes and a soft ''we''re aligned.'' Ask the two questions you ask on every late-stage call. Say them exactly.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'I ask two questions at every late-stage call: ''On a scale of 1-10, how aligned is your team on doing this?'' and ''What has to happen between now and signature?'' If either answer is fuzzy, the deal isn''t where I think it is — and I''d rather find out today than at the buzzer.',
  drill_rubric = '[{"c": "Asks alignment on a 1-10 scale explicitly", "must": true}, {"c": "Asks ''what has to happen between now and signature'' (path-to-signature question)", "must": true}, {"c": "Frames fuzzy answers as signal \u2014 surface the risk today, not at the buzzer", "must": true}, {"c": "Both questions delivered on EVERY late-stage call as a rule, not situational", "must": false}]'::jsonb,
  drill_teach_script = 'Late-stage deals lie to you when you only listen. Two questions on every late-stage call. First: on a scale of one to ten, how aligned is your team on doing this. Second: what has to happen between now and signature. If either answer is fuzzy, the deal is softer than the room sounds — and you''d rather find that out today than at the buzzer. Ask both, every call, no exceptions.',
  drill_ready = true
WHERE concept_id = 'CLS01' AND ki_id = '0fcbf135-2983-4d80-aaf3-d43fc5eda5be';

UPDATE public.ki_curriculum SET
  drill_scenario = 'DAZN, sports streaming, $2.1M ACV Branch Universal Ads expansion. Verbal from the head of paid social 20 days ago, then radio silence. Two ''just checking in'' emails, both ignored. Your manager wants a pipeline update tomorrow. You could send a third check-in — or engineer a real reason for them to re-engage. Their vertical is live sports OTT; you''ve got fresh benchmark data on Universal Ads CTV re-engagement lift from three peer streamers.',
  drill_spoken_task = 'You''re about to draft the outreach. State your rule for re-engaging this stall and the specific move you''re making with DAZN — no check-ins.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'When a deal stalls, I don''t ''check in'' — I create a real reason to engage. New data, a peer case study from their exact use case, a benchmark that says they''re 18 months behind the market. Generic follow-ups train them to ignore me.',
  drill_rubric = '[{"c": "Explicit rejection of ''check in'' / generic follow-up as the move", "must": true}, {"c": "Names a concrete re-engagement asset \u2014 new data, peer case study, or market benchmark", "must": true}, {"c": "Asset is specific to their vertical / use case (live sports OTT / streamer benchmark), not generic", "must": true}, {"c": "Names the cost of generic follow-ups \u2014 trains buyer to ignore you", "must": false}]'::jsonb,
  drill_teach_script = 'Stalled deals don''t need a nudge — they need a reason. ''Just checking in'' trains the buyer to ignore you, because you''ve told them there''s nothing new. Your rule when a deal stalls: bring a real reason to engage. New data, a peer case study from their exact use case, a benchmark that shows they''re eighteen months behind the market. If you can''t name a specific asset, you''re not ready to send the email yet.',
  drill_ready = true
WHERE concept_id = 'VEL02' AND ki_id = '4c29d8a9-8d97-4053-a4bb-a83985e20915';

UPDATE public.ki_curriculum SET
  drill_scenario = 'MeridianAir, $1.9M ACV Branch deal, close date March 28. You''re on a MAP-review call with your champion Elena, the Director of Digital. The MAP has 14 line items — 6 have your name and a date, 8 have Elena''s team names but no dates (''security review — TBD,'' ''legal — TBD,'' ''procurement kickoff — TBD''). Elena says, ''Let''s just leave the buyer-side dates open until we know more.'' You cannot let the call end with those TBDs.',
  drill_spoken_task = 'Elena wants to leave the buyer-side dates as TBD. Push back — say what the rule is and what you''re asking her to put next to the security review line right now.',
  drill_response_shape = 'talk_track',
  drill_model_answer = 'Every line in the MAP has an OWNER and a DATE on the buyer side — not just mine. If they won''t put their security review on a date, the MAP is fiction and the deal isn''t real. I push back: ''What''s blocking us from putting March 14 next to this?''',
  drill_rubric = '[{"c": "States the rule \u2014 every line has BOTH an owner and a date on the buyer side, not just yours", "must": true}, {"c": "Names the consequence of TBDs \u2014 MAP is fiction / deal isn''t real", "must": true}, {"c": "Actually pushes back with a specific proposed date (''what''s blocking us from putting [date] next to this'')", "must": true}, {"c": "Does not accept ''leave dates open until we know more'' as the outcome", "must": false}]'::jsonb,
  drill_teach_script = 'A mutual action plan without buyer-side dates is a wishlist. Every line needs an owner and a date on their side, not just yours. If your champion won''t put their security review on a date, the MAP is fiction and the deal isn''t real — you just don''t know it yet. Push back with a specific date: what''s blocking us from putting March fourteenth next to this. Force the conversation about what''s actually blocking, not whether to be vague.',
  drill_ready = true
WHERE concept_id = 'MAP02' AND ki_id = '20071a31-3a0f-4bc4-9408-bb40a2f3b8dd';
