/**
 * ArtifactInlineCard — premium summary card rendered inline in the chat
 * stream when a thread has a completed deep-work artifact.
 *
 *   ┌──────────────────────────────────────────────────────────┐
 *   │ 📄  Discovery Prep — Acme Inc.                           │
 *   │     12 sections · 8 library-backed · 2 redlines pending  │
 *   │     ▣  In thread · Sephora                               │  ← contextual stamp
 *   │                                                          │
 *   │   [ Open artifact ]  [ Copy ]  [ ⤓ ]  [ ↗ Promote ]      │
 *   └──────────────────────────────────────────────────────────┘
 *
 * Strategy outputs are contextual (they belong to a thread + optional
 * account/opportunity). They are NOT in the Library by default. The
 * "Promote to Library" action explicitly turns this output into a
 * reusable Library item. Promotion is the only path into the Library.
 *
 * Pure presentation — no data-mutation. Open & Promote are wired by
 * the parent (StrategyShell).
 */
import { FileText, ExternalLink, Copy, Download, BookmarkPlus, Lock } from 'lucide-react';
import { toast } from 'sonner';
import type { TaskRunResult } from '@/hooks/strategy/useTaskExecution';

interface Props {
  title: string;
  result: TaskRunResult;
  /** Was this artifact generated by an in-progress run that just completed? */
  freshlyCompleted?: boolean;
  /** Human label for the contextual scope, e.g. "Sephora" or "Acme — Q4 deal". */
  contextLabel?: string | null;
  onOpen: () => void;
  /** Open the Promote-to-Library form for this output. */
  onPromote?: () => void;
}

function buildSummary(title: string, result: TaskRunResult): string {
  const sections = result.draft.sections ?? [];
  const lines: string[] = [`${title}`, ''];
  for (const s of sections) {
    lines.push(`## ${s.name}`);
    lines.push('');
    const c = s.content;
    if (typeof c === 'string') lines.push(c);
    else if (c && typeof c === 'object') {
      try { lines.push(JSON.stringify(c, null, 2)); } catch { /* ignore */ }
    }
    lines.push('');
  }
  return lines.join('\n').trim();
}

export function ArtifactInlineCard({
  title, result, freshlyCompleted, contextLabel, onOpen, onPromote,
}: Props) {
  const sections = result.draft.sections ?? [];
  const sectionCount = sections.length;
  const libraryUsed = result.review.library_coverage?.used?.length ?? 0;
  const pendingRedlines = (result.review.redlines ?? []).filter(r => r.status === 'pending').length;

  const headline = freshlyCompleted
    ? `Your ${title} is ready.`
    : title;

  const stats: string[] = [];
  stats.push(`${sectionCount} section${sectionCount === 1 ? '' : 's'}`);
  if (libraryUsed > 0) stats.push(`${libraryUsed} library-backed`);
  if (pendingRedlines > 0) stats.push(`${pendingRedlines} edit${pendingRedlines === 1 ? '' : 's'} suggested`);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildSummary(title, result));
      toast.success('Summary copied');
    } catch {
      toast.error('Could not copy to clipboard');
    }
  };

  // Contextual scope line — makes it obvious this output is *contextual*,
  // not a library item. Mirrors the "Promote to Library" action below.
  const scopeText = contextLabel
    ? `In thread · ${contextLabel}`
    : 'In thread';

  return (
    <div
      data-strategy-artifact-card
      className={`rounded-[10px] my-2 ${freshlyCompleted ? 'sv-artifact-highlight' : 'sv-enter-fade'}`}
      style={{
        border: '1px solid hsl(var(--sv-hairline))',
        background: 'hsl(var(--sv-paper))',
        boxShadow: 'var(--sv-shadow-e1)',
      }}
    >
      <div className="px-4 py-3.5">
        <div className="flex items-start gap-2.5">
          <div
            className="h-8 w-8 rounded-[8px] flex items-center justify-center shrink-0"
            style={{ background: 'hsl(var(--sv-clay) / 0.1)', color: 'hsl(var(--sv-clay))' }}
          >
            <FileText className="h-4 w-4" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-[14px] font-semibold tracking-tight" style={{ color: 'hsl(var(--sv-ink))' }}>
              {headline}
            </p>
            {stats.length > 0 && (
              <p className="text-[12px] mt-0.5" style={{ color: 'hsl(var(--sv-muted))' }}>
                {stats.join(' · ')}
              </p>
            )}
            {/* Contextual stamp — distinguishes Work output from Library item */}
            <div className="mt-1.5 inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10.5px]"
              style={{
                background: 'hsl(var(--sv-hover) / 0.7)',
                color: 'hsl(var(--sv-muted))',
                border: '1px solid hsl(var(--sv-hairline))',
              }}
              title="This output is contextual to your thread. Use “Promote to Library” to make it reusable."
            >
              <Lock className="h-2.5 w-2.5" />
              <span>{scopeText}</span>
              <span aria-hidden style={{ opacity: 0.5 }}>·</span>
              <span>not in Library</span>
            </div>
          </div>
        </div>

        <div className="mt-3 flex flex-wrap items-center gap-1.5">
          {/* Primary action — the only filled button so the eye lands here */}
          <button
            onClick={onOpen}
            aria-label="Open artifact workspace"
            data-testid="strategy-open-artifact"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[6px] text-[12px] font-medium transition-colors"
            style={{
              background: 'hsl(var(--sv-clay))',
              color: 'white',
            }}
            onMouseEnter={(e) => { e.currentTarget.style.opacity = '0.9'; }}
            onMouseLeave={(e) => { e.currentTarget.style.opacity = '1'; }}
          >
            <ExternalLink className="h-3 w-3" />
            Open artifact
          </button>

          {/* Promote to Library — explicit, never automatic */}
          {onPromote && (
            <button
              onClick={onPromote}
              aria-label="Promote to Library"
              data-testid="strategy-promote-to-library"
              className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-[6px] text-[11.5px] font-medium transition-colors"
              style={{
                background: 'transparent',
                color: 'hsl(var(--sv-ink))',
                border: '1px solid hsl(var(--sv-hairline))',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = 'hsl(var(--sv-hover))'; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
              title="Save this as reusable knowledge in your Library"
            >
              <BookmarkPlus className="h-3 w-3" />
              Promote to Library
            </button>
          )}

          {/* Secondary actions — icon-only, borderless, low weight */}
          <button
            onClick={handleCopy}
            className="inline-flex items-center justify-center h-7 w-7 rounded-[6px] sv-hover-bg transition-colors"
            style={{ color: 'hsl(var(--sv-muted))' }}
            aria-label="Copy summary"
            title="Copy summary"
          >
            <Copy className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={onOpen}
            className="inline-flex items-center justify-center h-7 w-7 rounded-[6px] sv-hover-bg transition-colors"
            style={{ color: 'hsl(var(--sv-muted))' }}
            aria-label="Export"
            title="Export options live in the artifact view"
          >
            <Download className="h-3.5 w-3.5" />
          </button>
        </div>

        {/* Momentum line — answers "what should I do next?" the moment the artifact lands */}
        <p
          className="mt-2.5 text-[11px]"
          style={{ color: 'hsl(var(--sv-muted) / 0.85)', fontFamily: 'var(--sv-sans)' }}
        >
          ↓ Ask a follow-up below to refine, or open the artifact to read &amp; export.
        </p>
      </div>
    </div>
  );
}
