/**
 * ArtifactInlineCard — premium summary card rendered inline in the chat
 * stream when a thread has a completed deep-work artifact.
 *
 *   ┌──────────────────────────────────────────────────────────┐
 *   │ 📄  Discovery Prep — Acme Inc.                           │
 *   │     12 sections · 8 library-backed · 2 redlines pending  │
 *   │                                                          │
 *   │   [ Open artifact ]  [ Copy summary ]  [ ⤓ .docx ]       │
 *   └──────────────────────────────────────────────────────────┘
 *
 * Pure presentation — no data-mutation. Open is wired by the parent
 * (StrategyShell) to open the right-side ArtifactWorkspace.
 */
import { FileText, ExternalLink, Copy, Download } from 'lucide-react';
import { toast } from 'sonner';
import type { TaskRunResult } from '@/hooks/strategy/useTaskExecution';

interface Props {
  title: string;
  result: TaskRunResult;
  /** Was this artifact generated by an in-progress run that just completed? */
  freshlyCompleted?: boolean;
  onOpen: () => void;
}

function buildSummary(title: string, result: TaskRunResult): string {
  const sections = result.draft.sections ?? [];
  const lines: string[] = [`${title}`, ''];
  for (const s of sections) {
    lines.push(`## ${s.name}`);
    lines.push('');
    const c = s.content;
    if (typeof c === 'string') lines.push(c);
    else if (c && typeof c === 'object') {
      try { lines.push(JSON.stringify(c, null, 2)); } catch { /* ignore */ }
    }
    lines.push('');
  }
  return lines.join('\n').trim();
}

export function ArtifactInlineCard({ title, result, freshlyCompleted, onOpen }: Props) {
  const sections = result.draft.sections ?? [];
  const sectionCount = sections.length;
  const libraryUsed = result.review.library_coverage?.used?.length ?? 0;
  const pendingRedlines = (result.review.redlines ?? []).filter(r => r.status === 'pending').length;

  const headline = freshlyCompleted
    ? `Your ${title} is ready.`
    : title;

  const stats: string[] = [];
  stats.push(`${sectionCount} section${sectionCount === 1 ? '' : 's'}`);
  if (libraryUsed > 0) stats.push(`${libraryUsed} library-backed`);
  if (pendingRedlines > 0) stats.push(`${pendingRedlines} edit${pendingRedlines === 1 ? '' : 's'} suggested`);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildSummary(title, result));
      toast.success('Summary copied');
    } catch {
      toast.error('Could not copy to clipboard');
    }
  };

  return (
    <div
      data-strategy-artifact-card
      className={`rounded-[10px] my-2 ${freshlyCompleted ? 'sv-artifact-highlight' : 'sv-enter-fade'}`}
      style={{
        border: '1px solid hsl(var(--sv-hairline))',
        background: 'hsl(var(--sv-paper))',
        boxShadow: 'var(--sv-shadow-e1)',
      }}
    >
      <div className="px-4 py-3.5">
        <div className="flex items-start gap-2.5">
          <div
            className="h-8 w-8 rounded-[8px] flex items-center justify-center shrink-0"
            style={{ background: 'hsl(var(--sv-clay) / 0.1)', color: 'hsl(var(--sv-clay))' }}
          >
            <FileText className="h-4 w-4" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-[14px] font-semibold tracking-tight" style={{ color: 'hsl(var(--sv-ink))' }}>
              {headline}
            </p>
            {stats.length > 0 && (
              <p className="text-[12px] mt-0.5" style={{ color: 'hsl(var(--sv-muted))' }}>
                {stats.join(' · ')}
              </p>
            )}
          </div>
        </div>

        <div className="mt-3 flex flex-wrap items-center gap-1.5">
          <button
            onClick={onOpen}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[6px] text-[12px] font-medium transition-colors"
            style={{
              background: 'hsl(var(--sv-clay))',
              color: 'white',
            }}
            onMouseEnter={(e) => { e.currentTarget.style.opacity = '0.9'; }}
            onMouseLeave={(e) => { e.currentTarget.style.opacity = '1'; }}
          >
            <ExternalLink className="h-3 w-3" />
            Open artifact
          </button>
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[6px] text-[12px] font-medium sv-hover-bg"
            style={{
              border: '1px solid hsl(var(--sv-hairline))',
              color: 'hsl(var(--sv-ink))',
            }}
          >
            <Copy className="h-3 w-3" />
            Copy summary
          </button>
          <button
            onClick={onOpen}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[6px] text-[12px] font-medium sv-hover-bg"
            style={{
              border: '1px solid hsl(var(--sv-hairline))',
              color: 'hsl(var(--sv-ink))',
            }}
            title="Export options live in the artifact view"
          >
            <Download className="h-3 w-3" />
            Export
          </button>
        </div>
      </div>
    </div>
  );
}
